name: 'Tests: pretest/posttest'

on: [pull_request, push]

jobs:
  pretest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - eslint-config-oceanai

    defaults:
      run:
        working-directory: "packages/${{ matrix.package }}"

    steps:
      - name: Checkout code  
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ matrix.package }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-${{ matrix.package }}-node-

      - name: Setup Node.js
        uses: ljharb/actions/node/install@main
    
        with:
          node-version: 'lts/*'
      
      - name: Install dependencies
        run: npm install

      - name: Run pretest
        run: npm run pretest

