name: 'Publish: npm publish'

on: [push, pull_request]
      
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - eslint-config-oceanai

    defaults:
      run:
        working-directory: "packages/${{ matrix.package }}"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: ljharb/actions/node/install@main
      name: 'nvm install lts/* && npm install'
      with:
        node-version: 'lts/*'

    - name: Run tests
      run: npm test

  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - eslint-config-oceanai
          - eslint-config-oceanai-react

    defaults:
      run:
        working-directory: "packages/${{ matrix.package }}"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check for changes in package
      id: check_changes
      run: |
        git fetch
        CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- "packages/${{ matrix.package }}")
        if [[ -z "$CHANGED" ]]; then
          echo "No changes in ${{ matrix.package }} since last commit."
          echo "::set-output name=changed::false"
        else
          echo "Changes detected in ${{ matrix.package }}."
          echo "::set-output name=changed::true"
        fi
      continue-on-error: true

    - uses: actions/setup-node@v3
      if: steps.check_changes.outputs.changed == 'true'
      with:
        node-version: 'lts/*'
        registry-url: "https://registry.npmjs.org"
    - run: npm install
      if: steps.check_changes.outputs.changed == 'true'

    - name: Publish to npm
      if: steps.check_changes.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
