name: 'Publish: npm publish'

on:
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - eslint-config-oceanai

    defaults:
      run:
        working-directory: "packages/${{ matrix.package }}"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: ljharb/actions/node/install@main
      name: 'nvm install lts/* && npm install'
      with:
        node-version: 'lts/*'

    - name: Run tests
      run: npm test

  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - eslint-config-oceanai

    defaults:
      run:
        working-directory: "packages/${{ matrix.package }}"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}